version: '3.8'

services:
  svm-backend:
    build:
      context: ./SVM
    ports:
      - "5002:5000"
    networks:
      - app-network

  vgg-backend:
    build:
      context: ./vgg
    ports:
      - "5009:5001"
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend/my-angular-app
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
